build:
	pdflatex 5_1_einfuerungsbericht_yannik_noe.tex
	pdflatex 5_1_einfuerungsbericht_yannik_noe.tex
	open 5_1_einfuerungsbericht_yannik_noe.tex

clean:
	rm -f *.aux
	rm -f *.log
	rm -f *.pdf
	rm -f *.out
