build:
	pdflatex 6_1_abschlussbericht_yannik_noe.tex
	pdflatex 6_1_abschlussbericht_yannik_noe.tex
	open 6_1_abschlussbericht_yannik_noe.pdf

clean:
	rm -f *.aux
	rm -f *.log
	rm -f *.pdf
	rm -f *.out
	rm -f *.toc
