build:
	pdflatex 4_1_realisierungsbericht_yannik_noe.tex
	pdflatex 4_1_realisierungsbericht_yannik_noe.tex
	open 4_1_realisierungsbericht_yannik_noe.pdf

clean:
	rm -f *.aux
	rm -f *.log
	rm -f *.pdf
	rm -f *.out
